source = ~/.config/omarchy/generated/hyprlock-theme.conf

general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/omarchy/current/background
    blur_passes = 2
    blur_size = 6
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 280, 64
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff99">Password</span>
    hide_input = false
    check_color = $check_color
    fail_color = rgba(f38ba8ff)
    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $font_color
    font_size = 72
    font_family = Iosevka Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    color = $font_color
    font_size = 18
    font_family = Iosevka Nerd Font
    position = 0, 92
    halign = center
    valign = center
}
