splash = false
wallpaper {
    monitor = eDP-1
    path = /home/thadeu/.config/omarchy/themes/kanagawa/backgrounds/omarchy.png
    fit_mode = cover
}
wallpaper {
    monitor = DP-1
    path = /home/thadeu/.config/omarchy/themes/kanagawa/backgrounds/omarchy.png
    fit_mode = cover
}
